name: Run main.py periodically
# Trigger the workflow periodically using a cron schedule
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

  #schedule:
  #- cron: '0 6,10,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Checkout the repository content to GitHub runner
      - name: Checkout repository
        uses: 'actions/checkout@v4'
      - name: 'Authenticate with Google'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      # Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # Install dependencies from requirements.txt
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create token.json file
        run: |
            echo ${{ secrets.CYPRESS_CONFIG_JSON }} | base64 -d > token.json
          
  
      - name: Display file creation 
        run: |
            if [ -f "token.json" ]; then echo "token.json created"; fi
      # Run the Python script (main.py)
      - name: Execute Python script
        run: python main.py
      - name: Clean up token.json
        run: |
            rm -f token.json